spring.application.name=movies_app

#Configuración Base Datos
spring.datasource.url=jdbc:oracle:thin:@eeg7gozk9ct7wyk1_medium?TNS_ADMIN=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create-drop


