spring.application.name=movies_app

#Database Configuration
spring.datasource.url=jdbc:oracle:thin:@eeg7gozk9ct7wyk1_medium?TNS_ADMIN=/Users/jp/IdeaProjects/movies_app/Wallet_EEG7GOZK9CT7WYK1
spring.datasource.username=movieApp_user
spring.datasource.password=Movie_user123456#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create-drop


